# docker-compose.yml

version: '3.8'

services:
  # Naming the service "autobot" for clarity
  autobot:
    # Build the image from the Dockerfile in the current directory
    build: .

    # Name the running container "autobot"
    container_name: autobot

    # Always restart the bot if it crashes or the server reboots
    restart: always
    #token
    env_file:
      - .env
    dns:
      - 8.8.8.8